replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/c72cba-tools/docgen-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "test"

resources:
  cpu: 200m
  memory: 300Mi

database:
  secret: docgen-patroni
  service:
    name: docgen-patroni
    port: 5432



service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

auth:
  jwt:
    alg: RS256
    aud: epic-docgen
    cacheEnabled: true
    issuer: https://test.loginproxy.gov.bc.ca/auth/realms/eao-epic
    cacheTimeout: "300"
    wellKnownConfig: https://test.loginproxy.gov.bc.ca/auth/realms/eao-epic/.well-known/openid-configuration
  keycloak:
    uri: https://test.loginproxy.gov.bc.ca
    realm:
    adminClientId:
    adminClientSecret:
python:
  pythonBuffered: 1
  connectTimeout: 60
