"""template_id changed to template_key

Revision ID: 613374d9944e
Revises: bd07a716c6d5
Create Date: 2025-03-27 18:59:06.575985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613374d9944e'
down_revision = 'bd07a716c6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_key', sa.String(), nullable=False, comment='The unique identifier of the template'))
        batch_op.drop_index('unique_non_deleted_template_id', postgresql_where='false')
        batch_op.create_index('unique_non_deleted_template_key', ['template_key'], unique=True, postgresql_where=False)
        batch_op.drop_column('template_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='The unique identifier of the template'))
        batch_op.drop_index('unique_non_deleted_template_key', postgresql_where=False)
        batch_op.create_index('unique_non_deleted_template_id', ['template_id'], unique=True, postgresql_where='false')
        batch_op.drop_column('template_key')

    # ### end Alembic commands ###
