"""Type change for template id

Revision ID: bd07a716c6d5
Revises: ec7d6dd1dc59
Create Date: 2025-03-27 18:48:36.765361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd07a716c6d5'
down_revision = 'ec7d6dd1dc59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('template_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_comment='The unique identifier of the template',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('template_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_comment='The unique identifier of the template',
               existing_nullable=False)

    # ### end Alembic commands ###
