"""template table creation

Revision ID: ec7d6dd1dc59
Revises: 
Create Date: 2025-03-03 21:59:50.143493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7d6dd1dc59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app', sa.String(), nullable=False, comment='The name of the app where the template belongs'),
    sa.Column('template_id', sa.Integer(), nullable=False, comment='The unique identifier of the template'),
    sa.Column('template_content', sa.String(), nullable=False, comment='The html template content'),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index('unique_non_deleted_template_id', ['template_id'], unique=True, postgresql_where=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index('unique_non_deleted_template_id', postgresql_where=False)

    op.drop_table('templates')
    # ### end Alembic commands ###
